CREATE TABLE ENFERMERA(
ID NUMBER(2) NOT NULL,
NOMBRE VARCHAR2(25) NOT NULL,
APELLIDO VARCHAR2(25) NOT NULL,
SALARIO NUMBER(10) NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE CIUDAD(
ID NUMBER(2) NOT NULL,
NOMBRE VARCHAR(25) NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE MEDICO(
ID NUMBER(2) NOT NULL,
NOMBRE VARCHAR2(25) NOT NULL,
APELLIDO VARCHAR2(25) NOT NULL,
SALARIO NUMBER(10) NOT NULL,
ID_JEFE NUMBER(2),
CIUDAD NUMBER(2),
PRIMARY KEY(ID),
FOREIGN KEY (ID_JEFE) REFERENCES MEDICO(ID),
FOREIGN KEY (CIUDAD) REFERENCES CIUDAD(ID)
);

CREATE TABLE MEDICOXENFERMERA(
ID_MEDICO NUMBER(2),
ID_ENFERMERA NUMBER(2),
PRIMARY KEY(ID_MEDICO,ID_ENFERMERA),
FOREIGN KEY (ID_MEDICO) REFERENCES MEDICO(ID),
FOREIGN KEY (ID_ENFERMERA) REFERENCES ENFERMERA(ID)
);

CREATE TABLE ESPECIALIDAD(
ID NUMBER(2) NOT NULL,
NOMBRE VARCHAR2(25) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE ESPECIALIDADXMEDICO(
ID_ESPECIALIDAD NUMBER(2) NOT NULL,
ID_MEDICO NUMBER(2) NOT NULL,
PRIMARY KEY(ID_ESPECIALIDAD,ID_MEDICO),
FOREIGN KEY (ID_MEDICO) REFERENCES MEDICO(ID),
FOREIGN KEY(ID_ESPECIALIDAD) REFERENCES ESPECIALIDAD(ID)
);

CREATE TABLE SEGURO(
ID NUMBER(2) NOT NULL,
NOMBRE VARCHAR2(25) NOT NULL,
DIRECCION VARCHAR2(50) NOT NULL,
CIUDAD NUMBER(2) NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY (CIUDAD) REFERENCES CIUDAD(ID)
);

CREATE TABLE PACIENTE(
ID NUMBER(2) NOT NULL,
NOMBRE VARCHAR2(25) NOT NULL,
APELLIDO VARCHAR2(25) NOT NULL,
FECHA_NACIMIENTO DATE NOT NULL,
CIUDAD NUMBER(2) NOT NULL,
SEGURO NUMBER(2) NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (CIUDAD) REFERENCES CIUDAD(ID),
FOREIGN KEY (SEGURO) REFERENCES SEGURO(ID)
);


CREATE TABLE VISITA(
ID NUMBER(2) NOT NULL,
NOMBRE VARCHAR2(25) NOT NULL,
APELLIDO VARCHAR2(25) NOT NULL,
TIEMPO_VISITA NUMBER(2) NOT NULL,
ID_PACIENTE NUMBER(2) NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID)
);

CREATE TABLE SEDE(
ID NUMBER(2) NOT NULL,
NOMBRE VARCHAR2(50) NOT NULL,
DIRECCION VARCHAR2(50) NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE PISO(
ID NUMBER(2) NOT NULL,
DESCRIPCION VARCHAR2(100) NOT NULL,
ID_SEDE NUMBER(2) NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY (ID_SEDE) REFERENCES SEDE(ID)
);

CREATE TABLE HABITACION(
ID NUMBER(2) NOT NULL,
ES_DOBLE VARCHAR2(2) NOT NULL,
ID_PISO NUMBER(2) NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(ID_PISO) REFERENCES PISO(ID)
);

CREATE TABLE HOSPITALIZACION(
ID_PACIENTE NUMBER(2) NOT NULL,
ID_HABITACION NUMBER(2) NOT NULL,
PRIMARY KEY(ID_PACIENTE,ID_HABITACION),
FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID),
FOREIGN KEY (ID_HABITACION) REFERENCES HABITACION(ID)
);


CREATE TABLE CONSULTORIO(
ID NUMBER(2) NOT NULL,
EQUIPO_ADICIONAL VARCHAR2(50),
ID_PISO NUMBER(2) NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(ID_PISO) REFERENCES PISO(ID)
);

CREATE TABLE CITA(
ID NUMBER(3) NOT NULL,
FECHA_CITA DATE,
DESCRIPCION_CITA VARCHAR2(100),
ID_MEDICO NUMBER(2) NOT NULL,
ID_PACIENTE NUMBER(2) NOT NULL,
ID_CIUDAD NUMBER(2) NOT NULL,
ID_CONSULTORIO NUMBER(2) NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(ID_MEDICO) REFERENCES MEDICO(ID),
FOREIGN KEY(ID_PACIENTE) REFERENCES PACIENTE(ID),
FOREIGN KEY(ID_CIUDAD) REFERENCES CIUDAD(ID),
FOREIGN KEY(ID_CONSULTORIO) REFERENCES CONSULTORIO(ID)
);

CREATE TABLE DIAGNOSTICO(
ID NUMBER(2) NOT NULL,
DESCRIPCION_DIAG VARCHAR2(100) NOT NULL,
ID_CITA NUMBER(2) NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(ID_CITA) REFERENCES CITA(ID)
);

CREATE TABLE MEDICAMENTO(
ID NUMBER(2) NOT NULL,
NOMBRE VARCHAR2(50) NOT NULL,
DESCRIPCION_MED VARCHAR2(100) NOT NULL,
FECHA_VENCIMIENTO DATE NOT NULL,
ID_DIAGNOSTICO NUMBER(2) NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(ID_DIAGNOSTICO) REFERENCES DIAGNOSTICO(ID)
);